import type { CSSProperties } from "react";

/** Styles local to the first-run setup dialog. */
export const WIZARD_STYLES = {
	overlay: {
		position: "fixed",
		inset: 0,
		display: "flex",
		alignItems: "flex-start",
		justifyContent: "center",
		padding: "24px 16px",
		overflowY: "auto",
		zIndex: 1000,
	},
	backdrop: {
		position: "fixed",
		inset: 0,
		margin: 0,
		padding: 0,
		border: "none",
		background: "var(--skn-modal-backdrop)",
		cursor: "pointer",
	},
	dialog: {
		position: "relative",
		zIndex: 1,
		display: "flex",
		flexDirection: "column",
		width: "100%",
		maxWidth: 680,
		maxHeight: "calc(100vh - 48px)",
		overflow: "hidden",
		background: "var(--skn-surface)",
		color: "var(--skn-text)",
		border: "1px solid var(--skn-border)",
		borderRadius: "var(--skn-radius)",
		boxShadow: "var(--skn-modal-shadow)",
	},
	header: {
		display: "flex",
		alignItems: "center",
		gap: "var(--skn-space-2)",
		padding: "16px 20px",
		borderBottom: "1px solid var(--skn-border)",
	},
	title: {
		flex: 1,
		margin: 0,
		fontSize: "var(--skn-font-display)",
		fontWeight: 600,
		color: "var(--skn-text)",
	},
	close: {
		minWidth: "var(--skn-control-height)",
		minHeight: "var(--skn-control-height)",
		background: "var(--skn-surface-raised)",
		color: "var(--skn-text)",
		border: "1px solid var(--skn-border)",
		borderRadius: "var(--skn-radius)",
		cursor: "pointer",
		fontSize: 18,
		lineHeight: 1,
	},
	body: { padding: "16px 20px", overflowY: "auto" },
	intro: {
		fontSize: "var(--skn-font-small)",
		color: "var(--skn-text-muted)",
		lineHeight: 1.45,
		margin: "0 0 12px",
	},
	footer: {
		display: "flex",
		alignItems: "center",
		flexWrap: "wrap",
		gap: "var(--skn-space-1)",
		padding: "12px 20px",
		borderTop: "1px solid var(--skn-border)",
	},
	footerHint: {
		flex: 1,
		minWidth: 200,
		fontSize: "var(--skn-font-small)",
		color: "var(--skn-text-muted)",
		lineHeight: 1.4,
	},
	group: { marginBottom: 16 },
	groupTitle: {
		fontSize: "var(--skn-font-body)",
		fontWeight: 600,
		margin: "0 0 6px",
		color: "var(--skn-text)",
	},
	row: {
		display: "flex",
		alignItems: "center",
		gap: 10,
		minHeight: "var(--skn-row-height)",
		padding: "var(--skn-space-half) 0",
		cursor: "pointer",
	},
	rowText: {
		fontSize: "var(--skn-font-body)",
		color: "var(--skn-text)",
	},
	subhead: {
		fontSize: "var(--skn-font-body)",
		fontWeight: 600,
		color: "var(--skn-text)",
		margin: "16px 0 4px",
	},
} satisfies Record<string, CSSProperties>;
